allowBuilds:
  '@fortawesome/fontawesome-common-types': false
  '@fortawesome/free-brands-svg-icons': false
  '@fortawesome/free-regular-svg-icons': false
  '@fortawesome/free-solid-svg-icons': false
  sharp: false
